version: "3.9"
services:
  db:
    container_name: db
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    ports:
      - '4306:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network
    environment:
      - MYSQL_DATABASE=symfony
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony
    networks:
      - backend-network
      - frontend-network
    secrets:
      - db-password
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend-network
    depends_on:
      - php
      - db

volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
    backend-network:
    frontend-network:
